#!/bin/bash

# installing dependencies
sudo apt install xclip python3 python3-gi python3-gi-cairo gir1.2-gtk-3.0

# setting configs
WORKING_DIR="$HOME/.copy-cat-tail/clipboard"
CONFIG_DIR="$HOME/.copy-cat-tail/config"
MAX_COPY_LIMIT=40

# creating working directories and config
mkdir -p $WORKING_DIR/copies
mkdir -p $CONFIG_DIR
touch $CONFIG_DIR/config
echo "WORKING_DIR=/$WORKING_DIR" > $CONFIG_DIR/config
echo "MAX_COPY_LIMIT=$MAX_COPY_LIMIT" >> $CONFIG_DIR/config
chmod +x $CONFIG_DIR/config

# porting executables
sudo cp display.py /usr/bin/copy-cat-tail-show
sudo chmod +x /usr/bin/copy-cat-tail-show
sudo cp server.sh /usr/bin/copy-cat-tail-server
sudo chmod +x /usr/bin/copy-cat-tail-server



